Effect: Allow
Action:
  - ssm:GetParameter
  - ssm:GetParameters
  - ssm:GetParametersByPath
Resource:
  - arn:aws:ssm:${self:provider.region}:*:parameter${self:custom.naming.ssmPrefix}*
  - arn:aws:ssm:${self:provider.region}:*:parameter${self:custom.naming.ssmPrefix}/*
  - arn:aws:ssm:${self:provider.region}:*:parameter/mvx/${self:provider.stage}/*
  - arn:aws:ssm:${self:provider.region}:*:parameter/mvx/${self:provider.stage}/**
