{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "WorkflowEventsQueue": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "QueueName": "dev-workflow-service-events",
        "VisibilityTimeout": 180,
        "ReceiveMessageWaitTimeSeconds": 20,
        "MessageRetentionPeriod": 1209600,
        "Tags": [
          {
            "Key": "Service",
            "Value": "workflow-service"
          },
          {
            "Key": "Stage",
            "Value": "dev"
          },
          {
            "Key": "Purpose",
            "Value": "WorkQueue"
          },
          {
            "Key": "ManagedBy",
            "Value": "serverless"
          }
        ]
      }
    },
    "WorkflowEventsQueueUrlParameter": {
      "Type": "AWS::SSM::Parameter",
      "Properties": {
        "Name": "/dev/workflow-service/SQS_QUEUE_URL",
        "Type": "String",
        "Description": "Workflow events queue URL",
        "Value": {
          "Ref": "WorkflowEventsQueue"
        },
        "Tags": {
          "Service": "workflow-service",
          "Stage": "dev"
        }
      }
    },
    "WorkflowEventsQueueArnParameter": {
      "Type": "AWS::SSM::Parameter",
      "Properties": {
        "Name": "/dev/workflow-service/SQS_QUEUE_ARN",
        "Type": "String",
        "Description": "Workflow events queue ARN",
        "Value": {
          "Fn::GetAtt": [
            "WorkflowEventsQueue",
            "Arn"
          ]
        },
        "Tags": {
          "Service": "workflow-service",
          "Stage": "dev"
        }
      }
    }
  }
}
