service:
  name: workflow-service
  root: workflow

source:
  # repository: MyvitalRx/Cf-testing
  repository: geekytechwhiz/ci
  branch: dev
  connectionArn: arn:aws:codeconnections:us-east-1:462778607085:connection/271c183a-9f2b-4625-af12-86cebfe37a16
  ciPath: workflow/ci

deployment:
  data: true
  infrastructure: true
  application: true

data:
  enabled: true
  type: dynamodb
  logicalId: WorkflowTable
  tableName: workflow-service-dev
  ownershipTags:
    Service: workflow-service
    Purpose: WorkflowTable
    ManagedBy: serverless

features:
  dynamodb: true
  sqs: true
  lambda: true
  apiGateway: true

ssm:
  prefix: /nvdev-use1-mvx/workflow-service
  required:
    - TABLE_NAME
    - TABLE_ARN
    - STREAM_ARN
    - SQS_QUEUE_URL
    - SQS_QUEUE_ARN

application:
  healthCheckPath: /health
  apiBaseUrlParameter: /nvdev-use1-mvx/workflow-service/api-base-url
  healthResponseContains: '"status": "healthy"'
  smokeTest: required
  buildProjectName: ""

changeDetection:
  data:
    - workflow/data/**
  infrastructure:
    - workflow/infrastructure/**
  application:
    - workflow/src/**
    - workflow/serverless.yml
    - workflow/config/**
  ci:
    - workflow/ci/**
    - workflow/package.json