#!/usr/bin/env bash
# Generate workflow/config/naming.yml from deployment context + resource suffixes.
# RESOURCE_NAME_PREFIX is supplied by the generic CI/CD pipeline (CodeBuild env).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SUFFIXES_FILE="$SERVICE_DIR/config/resource-suffixes.yml"
OUTPUT_FILE="$SERVICE_DIR/config/naming.yml"

STAGE="${STAGE:-dev}"
SERVICE_NAME="${SERVICE_NAME:-workflow-service}"
AWS_REGION="${AWS_REGION:-us-east-1}"

# shellcheck source=../../cicd/pipeline/scripts/derive-deployment-context.sh
source "$SERVICE_DIR/../cicd/pipeline/scripts/derive-deployment-context.sh"

if [ -z "${RESOURCE_NAME_PREFIX:-}" ]; then
  # Local/manual packaging: derive the same prefix the pipeline would compute for dev/us-east-1.
  RESOURCE_NAME_PREFIX="$(derive_resource_name_prefix nv "$STAGE" "$AWS_REGION" mvx)"
  echo "WARN: RESOURCE_NAME_PREFIX not set; derived local default: ${RESOURCE_NAME_PREFIX}" >&2
fi

if [ -z "${SSM_PREFIX:-}" ]; then
  SSM_PREFIX="$(derive_ssm_prefix "$RESOURCE_NAME_PREFIX" "$SERVICE_NAME")"
fi

if [ ! -f "$SUFFIXES_FILE" ]; then
  echo "ERROR: Missing resource suffix definitions: $SUFFIXES_FILE" >&2
  exit 1
fi

read_suffix() {
  local key="$1"
  local line
  line="$(grep -E "^[[:space:]]*${key}:[[:space:]]*" "$SUFFIXES_FILE" | head -1 || true)"
  if [ -z "$line" ]; then
    echo "ERROR: resource-suffixes.yml is missing ${key}" >&2
    exit 1
  fi
  line="${line#*:}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  line="${line#\"}"
  line="${line%\"}"
  line="${line#\'}"
  line="${line%\'}"
  printf '%s' "$line"
}

table_suffix="$(read_suffix tableSuffix)"
queue_suffix="$(read_suffix queueSuffix)"
event_bus_suffix="$(read_suffix eventBusSuffix)"
event_rule_suffix="$(read_suffix eventRuleSuffix)"
lambda_api_suffix="$(read_suffix lambdaApiSuffix)"
lambda_events_suffix="$(read_suffix lambdaEventsSuffix)"
api_suffix="$(read_suffix apiSuffix)"
lambda_role_suffix="$(read_suffix lambdaRoleSuffix)"

cat >"$OUTPUT_FILE" <<EOF
# GENERATED by workflow/ci/generate-naming.sh — do not edit manually.
# Consumes RESOURCE_NAME_PREFIX from the generic CI/CD deployment context.
resourceNamePrefix: ${RESOURCE_NAME_PREFIX}
ssmPrefix: ${SSM_PREFIX}

tableName: ${RESOURCE_NAME_PREFIX}-${table_suffix}
queueName: ${RESOURCE_NAME_PREFIX}-${queue_suffix}
eventBusName: ${RESOURCE_NAME_PREFIX}-${event_bus_suffix}
eventRuleName: ${RESOURCE_NAME_PREFIX}-${event_rule_suffix}
lambdaApiName: ${RESOURCE_NAME_PREFIX}-${lambda_api_suffix}
lambdaEventsName: ${RESOURCE_NAME_PREFIX}-${lambda_events_suffix}
apiName: ${RESOURCE_NAME_PREFIX}-${api_suffix}
lambdaRoleName: ${RESOURCE_NAME_PREFIX}-${lambda_role_suffix}
EOF

echo "Generated naming contract: $OUTPUT_FILE"
echo "  resourceNamePrefix=${RESOURCE_NAME_PREFIX}"
echo "  ssmPrefix=${SSM_PREFIX}"
echo "  tableName=${RESOURCE_NAME_PREFIX}-${table_suffix}"
