Effect: Allow
Action:
  - dynamodb:GetRecords
  - dynamodb:GetShardIterator
  - dynamodb:DescribeStream
  - dynamodb:ListStreams
Resource:
  - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.naming.tableName}/stream/*
