Effect: Allow
Action:
  - dynamodb:GetRecords
  - dynamodb:GetShardIterator
  - dynamodb:DescribeStream
  - dynamodb:ListStreams
Resource:
  - '{{resolve:ssm:${self:custom.naming.ssmPrefix}/STREAM_ARN}}'
