Effect: Allow
Action:
  - sqs:ReceiveMessage
  - sqs:DeleteMessage
  - sqs:GetQueueAttributes
  - sqs:ChangeMessageVisibility
Resource:
  - '{{resolve:ssm:${self:custom.naming.ssmPrefix}/SQS_QUEUE_ARN}}'
