Effect: Allow
Action:
  - sqs:ReceiveMessage
  - sqs:DeleteMessage
  - sqs:GetQueueAttributes
  - sqs:ChangeMessageVisibility
Resource:
  - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.naming.queueName}
